const $=id=>document.getElementById(id),f=(x,n=2)=>x===null||!Number.isFinite(x)?'—':x.toFixed(n),names=['短向 · 連續端 −M','短向 · 不連續端 −M','短向 · 跨中 +M','長向 · 連續端 −M','長向 · 不連續端 −M','長向 · 跨中 +M'];
const badge=(ok,label)=>`<span class="badge ${ok===null?'na':ok?'':'bad'}">${label??(ok?'通過':'不足')}</span>`;
let current=null;
$('rows').innerHTML=names.map((n,i)=>`<tr class="${i===3?'group-start':''}"><td>${n}</td><td id="c${i}"></td><td id="m${i}"></td><td id="a${i}"></td><td id="s${i}"></td><td><input id="spacing${i}" type="number" min="0.1" step="0.5" value="20" aria-label="${n}實配間距，公分"></td><td id="p${i}"></td><td id="status${i}"></td></tr>`).join('');
function values(){let p={};for(const k of Object.keys(DEFAULT)){if(!['dsl','dss','spacing'].includes(k))p[k]=$(k).value===''?NaN:Number($(k).value);} [p.dsl,p.dss]=$('boundary').value.split(',').map(Number);p.spacing=names.map((_,i)=>$('spacing'+i).value===''?NaN:Number($('spacing'+i).value));return p;}
function check(name,ok,info,ratio){return `<div class="check"><div class="check-top"><strong>${name}</strong>${badge(ok)}</div><p>${info}</p><div class="track"><div class="fill ${ok?'':'bad'}" style="width:${Math.min(100,Math.max(0,ratio*100))}%"></div></div></div>`;}
function render(){try{const p=values(),o=calculate(p);current=o;$('error').hidden=true;$('valid-results').hidden=false;$('wu').textContent=f(o.wu,3);$('load-breakdown').innerHTML=`樓板自重：${f(p.h/100,3)} × 2.4 = <strong>${f(o.selfWeight,3)}</strong> tf/m²<br>總靜載重 D總：${f(o.selfWeight,3)} + ${f(p.dead,3)} = <strong>${f(o.totalDead,3)}</strong> tf/m²`;$('overall').textContent=o.pass?'原碼範圍內通過':'原碼檢核有未通過項目';$('overall').className=o.pass?'':'bad-text';$('summary-text').textContent=`${o.rows.filter(x=>x.active).length} 處配筋需求 · 現行規範仍有待補算項目，見下方核對`; $('system').textContent=o.one?'單向板分支':'雙向板分支';$('edge-count').textContent=`DSL = ${p.dsl} · DSS = ${p.dss}`;
const w=Math.min(330,155/o.r),h=w*o.r,x=(520-w)/2,y=35,cy=y+h/2,cx=x+w/2;
const edge=(a,b,c,d,on)=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}" stroke="${on?'#007d75':'#8a9bb0'}" stroke-width="${on?6:2}" ${on?'':'stroke-dasharray="7 5"'}/>`;
$('plan').innerHTML=`<defs><pattern id="grid" width="15" height="15" patternUnits="userSpaceOnUse"><path d="M15 0H0V15" fill="none" stroke="#dfebf2" stroke-width=".8"/></pattern></defs><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="#f2f7fa"/><rect x="${x}" y="${y}" width="${w}" height="${h}" fill="url(#grid)"/>${edge(x,y,x+w,y,p.dsl<2)}${edge(x,y+h,x+w,y+h,p.dsl===0)}${edge(x,y,x,y+h,p.dss<2)}${edge(x+w,y,x+w,y+h,p.dss===0)}<text x="${cx}" y="${cy+5}" text-anchor="middle" font-size="17" fill="#314d67">h = ${f(p.h,1)} cm</text><text x="${cx}" y="${y+h+35}" text-anchor="middle" font-size="15" fill="#526a82">L = ${f(p.long,2)} m</text><text x="50" y="${cy}" text-anchor="middle" font-size="14" fill="#526a82" transform="rotate(-90 50 ${cy})">S = ${f(p.short,2)} m</text><text x="${cx}" y="${y+h+62}" text-anchor="middle" font-size="13" fill="#526a82">S / L = ${f(o.r,3)} · d = ${f(o.d,1)} cm</text>`;
const steelRatio=Math.max(0,...o.rows.filter(x=>x.active).map(x=>x.req===null?2:Math.max(x.req/x.provided,x.spacing/x.maxSpacing)));
$('checks').innerHTML=check('最小板厚',o.thicknessPass,`h ${f(p.h)} / hmin ${f(o.hmin)} cm`,o.hmin/p.h)+check('剪應力',o.shearPass,`vu ${f(o.vu)} / vc ${f(o.vc)} kgf/cm²`,o.vu/o.vc)+check('配筋與間距',o.rows.every(x=>x.pass),`最大需求 / 容許比 ${f(steelRatio*100,1)}%`,steelRatio);
o.rows.forEach((r,i)=>{ $('c'+i).textContent=f(r.coef*1000,1);$('m'+i).textContent=f(r.mu,3);$('a'+i).textContent=f(r.req);$('s'+i).textContent=r.suggested===null?'—':`#${p.bar}@${f(r.suggested,1)}`;$('p'+i).textContent=f(r.provided);$('status'+i).innerHTML=r.req===null?badge(false,'超出斷面能力'):!r.active?badge(null,'無需求'):badge(r.pass,r.pass?'通過':r.provided<r.req?'面積不足':'間距過大');});
$('warnings').innerHTML=o.warnings.map(w=>`<div class="note">${w}</div>`).join('');
$('flow').innerHTML=`<p>先以板厚自動計入樓板自重，再依原碼標號 630–980 以總靜載與活載計算；r &lt; 0.5 採單向板，否則採雙向板係數表。DSL 為兩條長邊中不連續邊數，DSS 為兩條短邊中不連續邊數。</p><div class="formula">樓板自重 = ${p.h} / 100 × 2.4 = ${f(o.selfWeight,3)} tf/m²<br>D總 = 自重 + 額外 D = ${f(o.selfWeight,3)} + ${p.dead} = ${f(o.totalDead,3)} tf/m²<br>wᵤ = 1.2D總 + 1.6Lₗ = 1.2 × ${f(o.totalDead,3)} + 1.6 × ${p.live} = ${f(o.wu,3)} tf/m²<br>r = ${p.short} / ${p.long} = ${f(o.r,5)}<br>${o.one?'單向板：依 DSL 採用原碼固定係數。':`j = floor(floor(100r) / 2) − 24 = ${o.index}<br>取級 r = ${f(.48+.02*o.index,2)}；長向固定取 j = 26`}</div><p>單向短向係數（連續端、不連續端、跨中）：DSL=0 → 0.11、0、0.063；DSL=1 → 0.11、0.033、0.08999999；DSL=2 → 0、0.033、0.125。雙向依 D1 = DSL + DSS + 1 選列：D1=1 用 1、2 列；D1=5 用 12、13 列；其餘用 3(D1−2)+3 起的三列，再依邊界將不適用端係數歸零。</p>`;
$('steel-formula').innerHTML=`<p>標號 1050–1100、1620–1770、2130–2175。以 100 cm 寬板帶計算；每個位置各自計算 Aₛ。</p><div class="formula">|Mᵤ| = floor(C × S² × wᵤ × 1000) / 1000<br>d = ${p.h} − ${p.cover} = ${f(o.d)} cm<br>m₁ = fy / (0.8499999 f′c)<br>m₂ = |Mᵤ| × 1000 / (0.9000001 d²)<br>Aₛ,flex = [1 − √(1 − 2m₂m₁ / fy)] / m₁ × 100d<br>ρmin = ${o.rho}；Aₛ,min = ρmin × 100h = ${f(o.amin)} cm²/m<br>s建議 = min(floor(AAA / Aₛ × 10)/10, s上限)<br>本號數 AAA = ${BARS[p.bar][1]}；Ab = ${BARS[p.bar][0]} cm²<br>Aₛ,實配 = 100Ab / s</div><p>非零彎矩處以 Aₛ,min 作下限；零彎矩處原碼維持 Aₛ=0。單向板長向另設 Aₛ,min。一般間距上限為 2h，單向板長向為 45 cm。負根號表示此反算式無實數解，停止給出該處建議間距。</p>`;
$('shear-formula').innerHTML=`<p>標號 1790–2000。原碼 CPS 固定為 0，剪力臨界截面扣除有效深度 d。下式保留原程式幾何與折減因數。</p><div class="formula">${o.one?`hmin = 100S / ${[28,24,20][p.dsl]}<br>V = wᵤ × (S/2 − d/100) × L ${p.dsl===1?'× 1.15':''}`:`B = [(2−DSL)L + (2−DSS)S] / [2(S+L)] = ${f(o.bts,3)}<br>hmin = min{100L(800+0.0712fy) / [36000+5000(L/S)(1+B)], 100L(800+0.0712fy)/36000}<br>S′ = S − d/100；L′ = L − d/100<br>V = wᵤ × (S′L′/2 − S′²/4)`}<br>hmin（截位）= ${f(o.hmin)} cm<br>V = ${f(o.V,4)} tf<br>vu = floor([V/L/d × 10 / 0.8499999] × 100)/100 = ${f(o.vu)} kgf/cm²<br>vc = floor(0.53√f′c × 100)/100 = ${f(o.vc)} kgf/cm²</div><p>原碼以 vu ≤ vc、h ≥ hmin 判斷。vu 已除原碼剪力折減因數，並非未折減的 Vu/(bd)。</p>`;
renderAudit(o);
if(typeof updateUX==='function')updateUX(o);
}catch(e){current=null;$('error').textContent=e.message;$('error').hidden=false;$('valid-results').hidden=true;$('load-breakdown').textContent='輸入未完整或無效，請修正後查看載重。';}}
$('params').addEventListener('input',render);$('params').addEventListener('change',render);$('params').addEventListener('submit',e=>e.preventDefault());$('rows').addEventListener('input',render);
$('reset').addEventListener('click',()=>{for(const k of Object.keys(DEFAULT))if(!['dsl','dss','spacing'].includes(k))$(k).value=DEFAULT[k];$('boundary').value='0,0';names.forEach((_,i)=>$('spacing'+i).value=20);render();});
$('coefficient-table').innerHTML=`<table><thead><tr><th>列 i / r</th>${Array.from({length:26},(_,j)=>`<th>${f(.5+j*.02,2)}</th>`).join('')}</tr></thead><tbody>${TABLE.slice(1).map((row,i)=>`<tr><td>${i+1}</td>${row.slice(1).map((v,j)=>`<td class="${i===3&&j===18||i===12&&j===17?'bad-text':''}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const pdf='https://www.nlma.gov.tw/uploads/files/011d9249cac7d6c5547786aa348e352a.pdf';
function source(section,page){return `<a href="${pdf}#page=${page}" target="_blank" rel="noopener">${section} ↗</a>`;}
const auditPanel=document.createElement('section');auditPanel.className='panel audit';auditPanel.innerHTML=`<div class="section-line"><h2>臺灣現行規範符合性核對</h2><span class="pill">112 年版 · 含 113 年勘誤</span></div><div class="note"><strong>整體結論：原程式需修正與補算，不能判定完整符合。</strong><br>下列即時檢查限非預力實心樓板的指定條款，不取代完整設計。原碼結果未因規範核對而被覆寫。</div><p class="hint">查核日：2026-10-01。依國土管理署公告，112 年版自 113-01-01 生效，並有 113-02-19 勘誤。<a href="https://www.nlma.gov.tw/ch/legislation/regsearch/6874" target="_blank" rel="noopener">官方版本公告</a> · <a href="${pdf}" target="_blank" rel="noopener">規範全文（含勘誤）</a></p><div id="audit-live"></div><details><summary>逐項差異、條文與尚缺資料</summary><div class="audit-list">
<article><h3>載重組合 ${source('表 5.3.1',63)}</h3><p>本版 D總 = 樓板自重 + 額外 D；以下規範條文中的 D 均指總靜載重。原碼僅 1.2D+1.6L。只有 D 與 L 的重力情況，亦應比較 1.4D；當 D&gt;8L，原碼組合可能低估。本頁只做兩組數值比較，其他屋頂、雨、風、震、土壓、溫度等須依實際作用納入。</p></article>
<article><h3>分析方法與係數 ${source('6.5、8.4.1',72)}</h3><p>附件係數表缺完整規範出處，不能僅憑九種邊界即認定是現行許可方法。6.5 簡法需均勻斷面、均布載重、L≤3D、至少兩跨及相鄰跨差異小於20%，並依各位置取係數。尚缺相鄰跨、支承尺寸及邊梁勁度；雙向板應以合適分析驗證。</p></article>
<article><h3>彎矩折減與有效深度 ${source('7.3.3、表 21.2.2',366)}</h3><p>原碼固定 φ≈0.90，未驗證拉力控制。現行拉力控制要求 εt≥εty+0.003；應依實配鋼筋、β₁、實際 d 計算。若輸入 c 指淨保護層，d=h−c 會漏扣鋼筋半徑與層位，不能直接作正式斷面檢核。此項資料不足。</p></article>
<article><h3>剪力折減及混凝土強度 ${source('表 21.2.1、表 22.5.5.1',365)}</h3><p>原碼採 φ≈0.85；現行一般剪力 φ=0.75（耐震另有規定），必須修正。無足量剪力筋時，現行 Vc 依表22.5.5.1(c)納入縱筋比 ρw、尺寸效應 λs、輕質修正 λ 及軸力，不能一律採 0.53√f′c bd。</p><div class="formula">Av &lt; Av,min：Vc = [2.12 λs λ ρw^(1/3) √f′c + Nu/(6Ag)] bwd<br>λs = min[1, √(2/(1+d/25))]（d：cm）<br>Vc ≤ 1.33 λ√f′c bwd；Vc ≥ 0</div><p>尚須確認臨界斷面鋼筋與錨定、實際 d、支承面位置及剪力分布。此頁不將僅換 φ 的數值冒充完整現行剪力計算。</p></article>
<article><h3>最少鋼筋 ${source('7.6.1.1、8.6.1、24.4.3',89)}</h3><p>一般最少撓曲及收縮溫度筋比為 0.0018。原碼 fy&lt;4200 採0.002，通常較保守；fy≥4200 最終採0.0018。雙向板柱邊或集中反力區，8.6.1.2可能另控制，須補沖切與 bslab 資料；本頁0.0018檢查不含此特殊要求。</p></article>
<article><h3>間距上下限 ${source('7.7.2、8.7.2、24.4.3.3',108)}</h3><p>單向主筋最大間距 min(3h,45 cm)，另受24.3裂縫控制；分布筋 min(5h,45 cm)。雙向臨界截面 min(2h,45 cm)。原碼一般只限制2h，缺45 cm絕對上限；薄單向板分布筋亦可能漏5h上限。最小淨間距另須依25.2及粒料尺寸檢核。</p></article>
<article><h3>板厚與撓度 ${source('7.3.1、8.3.1、24.2',86)}</h3><p>單向板表7.3.1.1需在fy≠4200時乘(0.4+fy/7000)，輕質混凝土亦需修正，並受隔間損害等適用條件限制。原碼未考慮。雙向現行公式依是否有梁、梁板勁度比αfm、淨跨及外邊梁條件決定；不能用原碼的連續邊比例B直接代替αfm。欠梁斷面、板帶與支承淨跨資料，故暫不能判定。</p></article>
<article><h3>構造與完整性 ${source('8.7、20.5、22.6、25',108)}</h3><p>原碼未驗算雙向沖切、不平衡彎矩傳遞、角隅補強、開孔影響、保護層耐久性、錨定及續接、收縮溫度束制。須依實際支承、暴露環境、鋼筋層位與配置詳圖另行核對。</p></article></div></details>`;
document.querySelector('.formulas').before(auditPanel);
function renderAudit(o){const p=o.p,grav=Math.max(1.4*o.totalDead,o.wu),min=.0018*100*p.h,active=o.rows.filter(r=>r.active),steelOk=active.every(r=>r.provided>=min),spacingOk=o.rows.every((r,i)=>!r.active||r.spacing<=Math.min(45,p.h*(o.one?(i<3?3:5):2)));
const row=(label,ok,value,ref)=>`<tr><td>${label}</td><td>${value}</td><td>${badge(ok,ok===null?'待補算':ok?'本項符合':'本項不足')}</td><td>${ref}</td></tr>`;
$('audit-live').innerHTML=`<div class="table-wrap"><table class="audit-table"><thead><tr><th>即時條款核對</th><th>目前數值 / 判讀</th><th>狀態</th><th>依據</th></tr></thead><tbody>${row('D、L 重力組合',o.wu>=1.4*o.totalDead,`原碼 ${f(o.wu,3)}；兩組包絡 ${f(grav,3)} tf/m²`,source('5.3.1',63))}${row('一般最少鋼筋量',steelOk,`0.0018 × 100h = ${f(min)} cm²/m；檢查有需求位置`,source(o.one?'7.6.1、24.4.3':'8.6.1.1',o.one?89:105))}${row('條文最大間距',spacingOk,o.one?`主筋 ≤ ${f(Math.min(3*p.h,45),1)}；分布筋 ≤ ${f(Math.min(5*p.h,45),1)} cm`:`臨界截面 ≤ ${f(Math.min(2*p.h,45),1)} cm`,source(o.one?'7.7.2.3、24.4.3.3':'8.7.2.2',o.one?91:108))}${row('原碼剪力 φ',false,'原碼 0.85 → 現行一般值 0.75，須重算',source('21.2.1',365))}${row('板厚與使用性',null,o.one?`常重混凝土表值參考 ${f(p.short*100/[28,24,20][p.dsl]*(.4+p.fy/7000))} cm；跨度定義及適用條件待確認`:'缺梁板勁度 αfm、淨跨、外邊梁等資料',source(o.one?'7.3.1':'8.3.1',o.one?86:97))}${row('分析、撓曲與剪力強度',null,'係數適用性、d、鋼筋應變、現行 Vc 與沖切待補算',source('第 6、8、21、22 章',103))}</tbody></table></div><p class="hint">本項符合僅代表上列明示數值限制，不代表整片樓板符合全部規範。最小鋼筋與最大間距仍需確認鋼筋實際分布、拉力面與其餘適用條件。</p>`;
}
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_slab_analysis',description:'讀取目前樓板輸入、原碼檢核結果與現行規範仍需補算的狀態。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){if(!current)throw Error('輸入無效');return {inputs:current.p,sourceChecksPass:current.pass,codeCompliance:'需修正與補算，未完成全規範檢核',slabSelfWeight:current.selfWeight,totalDeadLoad:current.totalDead,wu:current.wu,hmin:current.hmin,vu:current.vu,vc:current.vc};}})).catch(()=>{});}catch{}}
