(()=>{
 const q=id=>document.getElementById(id),num=(x,n=3)=>Number.isFinite(x)?x.toFixed(n):'—';
 const definitions={short:'短跨 S，單位 m。來源：結構平面及梁柱配置圖。須確認分析方法的淨跨／有效跨度定義，程式不自動扣梁寬。',long:'長跨 L，單位 m。來源：結構平面圖，需大於或等於短跨；交換方向時須同步確認邊界。',h:'結構板厚 h，cm；不含裝修層。來源：板厚表／剖面圖。自重自動採 h÷100×2.4 tf/m²。',cover:'歷史程式的有效深度扣除值 c，cm。原碼直接採 d=h−c；未扣半徑與層位。現行斷面複核請另填實際 d。',fc:'混凝土設計抗壓強度 f′c，kgf/cm²。來源：結構總說明或經評估採用的試驗值。',fy:'鋼筋設計降伏強度 fy，kgf/cm²。來源：結構總說明與鋼筋材質證明。',dead:'額外靜載重 D，tf/m²。只填裝修、隔間等永久重量，不含本板自重。来源：裝修圖與載重計算表；集中、線載重須另分析。',live:'活載重 Lₗ，tf/m²。依核定用途、專案設計準則及適用載重規定採值。200 kgf/m² 請填 0.200。',boundary:'依相鄰板跨、支承與端部配筋判斷。實線為連續邊；虛線是不連續支承邊，不是自由邊。DSL：長邊不連續數；DSS：短邊不連續數。',bar:'六處共用的鋼筋號數，單支面積依原始表。來源：樓板配筋圖。實配間距以 cm 輸入中心距；#4@150 mm 請填 15 cm。'};
 Object.entries(definitions).forEach(([id,text])=>{const input=q(id),label=input.closest('label'),detail=document.createElement('details');detail.className='field-help';detail.innerHTML='<summary>ⓘ 定義與資料來源</summary>';const p=document.createElement('p');p.id='definition-'+id;p.textContent=text.replace('来源','來源');detail.append(p);label.after(detail);input.setAttribute('aria-describedby',p.id);input.title=p.textContent;});
 const panel=document.createElement('section');panel.className='panel modern-panel';panel.id='modern-panel';panel.innerHTML=`<h2>現行規範斷面複核 <span class="pill">112 年版＋113 年勘誤</span></h2><p class="hint">查核日期 2026-10-10。限常重、非預力、無軸力、無剪力筋之單層受拉鋼筋矩形板帶（b＝100 cm）。輸入經確認之同一斷面 Mu、Vu 與實際有效深度。此模組不做整板內力分析或沖切。</p><div class="modern-fields"><label>複核位置<select id="modern-position">${names.map((n,i)=>`<option value="${i}">${n}</option>`).join('')}</select><small>使用所選位置的實配面積及間距。</small></label><label>板系統<select id="modern-system"><option value="two">雙向板臨界截面</option><option value="one">單向板主筋</option></select><small>由實際傳力系統判斷，不只看長短跨比。</small></label><label>實際有效深度 d（cm）<input id="modern-d" type="number" step="0.1" value="11.5" inputmode="decimal"><small>受壓緣到受拉筋重心；來源：配筋剖面，需扣淨保護層、半徑及層位。</small></label><label>設計彎矩 |Mu|（tf·m/m）<input id="modern-mu" type="number" min="0" step="0.01" value="1.2" inputmode="decimal"><small>來源：適用載重組合的結構分析，負彎矩區使用該拉力面的 d 與鋼筋。</small></label><label>設計單向剪力 |Vu|（tf/m）<input id="modern-vu" type="number" min="0" step="0.01" value="2" inputmode="decimal"><small>來源：同一板帶臨界斷面的剪力包絡；不是整片板總剪力。</small></label></div><p class="note">此處預設 Mu＝1.2、Vu＝2、d＝11.5 僅為示範，修改主表後不會自動更新這三個值；請依本次分析重新輸入。</p><div id="modern-output" aria-live="polite"></div><details><summary>條文、適用範圍與尚需檢核</summary><p>表21.2.2、7.3.3.1／8.3.3.1：板須為拉力控制；表22.2.2.4.3：β₁；7.6.1.1／8.6.1.1：一般最少筋；7.7.2.3／8.7.2.2：所選位置間距；表22.5.5.1(c)：無足量剪力筋 Vc；表21.2.1：一般剪力 φ＝0.75。</p><p>不包括柱邊特殊最少筋、雙向沖切、不平衡彎矩、撓度、裂縫控制、保護層耐久性、淨間距、錨定、開孔與耐震容量設計；須另行完成。縱筋比中的 As 必須是在剪力斷面有效錨定的拉力筋，兩種驗算位置不同時應分別輸入。</p><a href="https://www.nlma.gov.tw/ch/legislation/regsearch/6874" target="_blank" rel="noopener">官方版本公告</a> · <a href="https://www.nlma.gov.tw/uploads/files/011d9249cac7d6c5547786aa348e352a.pdf" target="_blank" rel="noopener">規範全文</a></details>`;
 document.querySelector('.audit').prepend(panel);
 window.modernReportLines=()=>{if(!window.modernCurrent)return ['現行斷面複核：輸入無效，未產生結果。'];return window.modernCurrent.lines;};
 window.updateModern=()=>{try{if(!current)throw Error('請先修正主表輸入。');const p=current.p,i=Number(q('modern-position').value),row=current.rows[i];const val=id=>q(id).value.trim()===''?NaN:Number(q(id).value);const o=SlabModern.section({h:p.h,fc:p.fc,fy:p.fy,as:row.provided,spacing:row.spacing,d:val('modern-d'),mu:val('modern-mu'),vu:val('modern-vu'),system:q('modern-system').value});const env=Math.max(1.4*current.totalDead,current.wu);
 const lines=[`現行規範斷面複核｜查核日 2026-10-10｜${names[i]}`,`僅常重、非預力、無軸力、無剪力筋、單層受拉筋之 100 cm 板帶；一般重力斷面檢查，並非整板合規。`,`需求為使用者輸入（初值為示範）：Mu=${num(o.mu)} tf·m/m；Vu=${num(o.vu)} tf/m。實際 d=${num(o.d)} cm。`,`h=${num(p.h)} cm；f′c=${num(p.fc)} kgf/cm²；fy=${num(p.fy)} kgf/cm²；As=${num(o.as,4)} cm²/m；s=${num(o.spacing)} cm。`,`D、L 重力組合：max[1.4×${num(current.totalDead)}, 1.2×${num(current.totalDead)}+1.6×${num(p.live)}]=${num(env)} tf/m²；此數值不自動代替外部分析內力。`,`β₁=max[0.65,min(0.85,0.85−0.05(f′c−280)/70)]=${num(o.beta,4)}。`,`力平衡：0.85f′c b β₁c=As×min[fy,Es×0.003(d−c)/c]；Es=2,040,000 kgf/cm²。`,`解得中性軸 c=${num(o.c,4)} cm；a=β₁c=${num(o.a,4)} cm；fs=${num(o.fs)} kgf/cm²。`,`εt=0.003(d−c)/c=${num(o.et,6)}；εty=fy/Es=${num(o.ey,6)}；拉力控制界限 εty+0.003=${num(o.ey+.003,6)}。`,`拉力控制：${o.tension?'符合':'不符合，板設計不可判定通過'}；φ=${num(o.phi,4)}（過渡區依表21.2.2內插）。`,`Mn=As fs(d−a/2)/100000=${num(o.mn,4)} tf·m/m；φMn=${num(o.capacity,4)} tf·m/m；Mu/φMn=${num(o.mu/o.capacity,4)}。`,`As,min=0.0018×100×${num(p.h)}=${num(o.amin)} cm²/m；間距上限 min(${o.system==='one'?'3':'2'}h,45)=${num(o.smax)} cm。`,`ρw=As/(100d)=${num(o.rho,6)}；λ=1；Nu=0；λs=min[1,√(2/(1+d/25))]=${num(o.lambdaS,5)}。`,`vc,raw=2.12×${num(o.lambdaS,5)}×1×${num(o.rho,6)}^(1/3)×√${num(p.fc)}=${num(o.vcRaw,4)} kgf/cm²。`,`vc上限=1.33√f′c=${num(o.vcLimit,4)} kgf/cm²；採 vc=${num(o.vc,4)} kgf/cm²。`,`Vc=vc×100×d/1000=${num(o.Vc,4)} tf/m；φVc=0.75Vc=${num(o.phiVc,4)} tf/m；Vu/φVc=${num(o.vu/o.phiVc,4)}。`,`結果：撓曲含拉力控制 ${o.flexPass?'通過':'不足'}；一般最少筋 ${o.minPass?'通過':'不足'}；所選位置間距 ${o.spacingPass?'通過':'不足'}；單向剪力 ${o.shearPass?'通過':'不足'}。`,`條文：5.3.1、7.3.3.1／8.3.3.1、7.6.1.1／8.6.1.1、7.7.2.3／8.7.2.2、21.2.1／21.2.2、22.2.2.4.3、22.5.5.1(c)。`,`仍需確認需求分析、鋼筋錨定、柱邊特殊最少筋、沖切、撓度、裂縫、淨間距及其他構造條件。`];
 window.modernCurrent={...o,lines};const esc=t=>t.replaceAll('&','&amp;').replaceAll('<','&lt;');q('modern-output').innerHTML=`<div class="modern-checks">${[['撓曲＋延展性',o.flexPass],['一般最少筋',o.minPass],['所選位置間距',o.spacingPass],['單向剪力',o.shearPass]].map(([t,ok])=>`<div>${t} ${badge(ok)}</div>`).join('')}</div><p class="note"><strong>${o.pass?'本模組四項通過；其餘設計條件仍待確認。':'本模組有未通過項目，請查看計算過程。'}</strong></p><details open><summary>公式、代入與結果（同步匯入 Word）</summary><div class="modern-trace">${lines.slice(2).map(t=>`<p>${esc(t)}</p>`).join('')}</div></details>`;
 }catch(e){window.modernCurrent=null;q('modern-output').textContent=e.message;}};
 panel.addEventListener('input',updateModern);panel.addEventListener('change',updateModern);updateModern();
 const quick=document.createElement('button');quick.type='button';quick.className='modern-jump';quick.textContent='現行斷面複核 →';quick.addEventListener('click',()=>{setWorkspaceView('analysis');q('tab-2').click();panel.scrollIntoView({block:'start'});});document.querySelector('.summary').append(quick);
})();
