// Fixed Taiwan female narration; no device-dependent speech synthesis.
(()=>{
 const chapters=[{"title": "工作台與資料準備", "start": 0, "text": "歡迎使用樓板分析設計工作台。請先準備結構平面、配筋圖、材料強度及載重表。手機可用底部按鈕切換參數、結果和報告。點開欄位下方的定義與資料來源，就能查詢填寫方式。"}, {"title": "幾何與支承條件", "start": 21.472, "text": "先輸入短跨、長跨與結構板厚，再選擇邊界條件。實線代表連續邊，虛線仍有支承，不是自由邊。歷史程式的保護層扣除值，不等於實際有效深度；新版斷面複核要另外輸入。"}, {"title": "自重與額外靜載重", "start": 41.864, "text": "額外靜載重不要重複填入板自重。例如板厚二十公分，程式自動算出每平方公尺零點四八公噸力，再加上裝修與隔間重量。活載重要依使用用途及適用載重規定填寫。"}, {"title": "配筋與即時結果", "start": 60.84, "text": "選擇鋼筋號數，再輸入六處實配間距。十五公分請填十五，不是以毫米填一百五十。可先統一套用，再逐處調整。原程式檢核結果保留供比對，不代表整片樓板已符合現行規範。"}, {"title": "現行規範斷面複核", "start": 81.808, "text": "開啟現行斷面複核，選擇位置及板系統，填入實際有效深度、分析彎矩與單向剪力。預設值只是示範。程式依一百一十二年版及一百一十三年勘誤，檢查撓曲、拉力控制、最少鋼筋、間距與單向剪力。"}, {"title": "計算書與其他必要檢核", "start": 104.744, "text": "展開公式可看完整代入過程。填妥工程名稱及樓板編號後，匯出可編輯的Word計算書。沖切、撓度、錨定及分析方法適用性仍須另外確認。操作說明與影片可隨時重新開啟查詢。"}];
 const dialog=document.createElement('dialog');dialog.id='tutorial-dialog';dialog.setAttribute('aria-labelledby','tutorial-title');
 dialog.innerHTML=`<div class="help-top"><div><h2 id="tutorial-title">樓板工作台・操作影片</h2><p>約 2 分鐘 · 台灣女性合成語音（曉臻）· 繁體中文字幕</p></div><button type="button" id="close-tutorial" aria-label="關閉操作影片">關閉 ✕</button></div><div class="tutorial-content"><video id="tutorial-video" controls playsinline preload="none" poster="media/tutorial-poster.jpg"><source src="media/tutorial.mp4" type="video/mp4"><track kind="captions" src="media/tutorial.zh-TW.vtt" srclang="zh-TW" label="繁體中文" default>您的瀏覽器無法播放影片，請使用下方下載連結。</video><nav class="tutorial-chapters" aria-label="影片章節">${chapters.map((c,i)=>`<button type="button" data-time="${c.start}"><b>${String(i+1).padStart(2,'0')}</b> ${c.title}</button>`).join('')}</nav><p class="hint">章節按鈕可跳到指定段落；第一次請按播放。示範數值並非專案設計值。</p><p><a href="media/tutorial.mp4" download>下載教學影片 MP4</a> · <a href="media/tutorial-transcript.txt" download>下載旁白文字稿</a></p><details><summary>閱讀完整旁白</summary>${chapters.map(c=>`<h3>${c.title}</h3><p>${c.text}</p>`).join('')}</details></div>`;
 document.body.append(dialog);const video=dialog.querySelector('video');
 function open(){dialog.showModal();}
 const button=document.createElement('button');button.id='open-tutorial';button.type='button';button.className='tutorial-launch';button.textContent='▶ 操作影片・台灣女聲';button.setAttribute('aria-haspopup','dialog');button.addEventListener('click',open);document.querySelector('.intro').append(button);
 const helpButton=button.cloneNode(true);helpButton.removeAttribute('id');helpButton.addEventListener('click',()=>{document.querySelector('#operation-help').close();open();});document.querySelector('.help-search').prepend(helpButton);
 dialog.querySelector('#close-tutorial').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>video.pause());
 dialog.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{const seek=()=>{video.currentTime=Number(b.dataset.time);};if(video.readyState===0){video.addEventListener('loadedmetadata',seek,{once:true});video.load();}else seek();}));
 document.getElementById('reset').addEventListener('click',()=>{[['modern-d','11.5'],['modern-mu','1.2'],['modern-vu','2'],['modern-position','0'],['modern-system','two']].forEach(([id,val])=>document.getElementById(id).value=val);updateModern();});
})();
